actors:
  watahari:
    image_url: /images/actors/watahari.png
    name: わたはり
    url: https://watahari.com/
  voltsss:
    image_url: /images/actors/voltsss.jpeg
    name: でんあつ
    url: https://twitter.com/voltsss
  chocowriter:
    image_url: /images/actors/chocowriter.jpg
    name: しょこらいたー
    url: https://twitter.com/chocowriter
  aoiroaoino:
    image_url: /images/actors/aoino.jpeg
    name: あおいの
    url: https://twitter.com/aoiroaoino
author: watahari
description: 高専卒の酔っぱらいが、お酒を飲みながら好き勝手にだべる雑談系Podcastです。技術・サブカル・趣味・ガジェット・・・なんでもありな雑談をラジオ風にお届けします。一緒に乾杯しませんか。
description_long: 元高専生の酔っぱらいが、お酒を飲みながら好き勝手にだべるPodcastです。きっと「あー、オタクの(いい意味で)面倒な飲み会ね」と思ってもらえるはずです。楽しかったけど翌日には記憶が怪しい、そんな飲み会を、Podcastの形でメモしておこうと思います。
email: admin@mamimumemo.online
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: G-YCXLK28HW9
twitter_id: mamimumemofm
hashtag: "まみむメモfm"
itunes_podcast_url: https://podcasts.apple.com/podcast/watahari/id1540412220
spotify_podcast_url: https://open.spotify.com/show/3yrZjPJTUvV5k2tCXO77vN
anchor_podcast_url: https://anchor.fm/mamimumemo
google_podcast_url: https://podcasts.google.com/feed/aHR0cHM6Ly9tYW1pbXVtZW1vLm9ubGluZS9mZWVkLnhtbA
keywords: 雑談,飲み会,酒,高専,高専卒,オタク,サブカル,インターネット
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: まみむメモ
url: https://mamimumemo.online/
